---
- name: Configure Apache.
  lineinfile:
    dest: "{{ apache_server_root }}/conf/{{ apache_daemon }}.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: {{ apache_ports_configuration_items | union(apache_configuration_items) }}
  notify: restart apache
  when: apache_httpdconf_file is not defined

- name: Override default Apache conf.
  template:
    src: "{{ apache_httpdconf_file }}"
    dest: "{{ apache_server_root }}/conf/{{ apache_daemon }}.conf"
    force: "{{ apache_httpdconf_file_force_overwrite | default('yes') }}"
  notify: restart apache
  when: apache_httpdconf_file is defined

- name: Check whether certificates defined in vhosts exist.
  stat: path={{ item.certificate_file }}
  register: apache_ssl_certificates
  with_items: "{{ apache_vhosts_ssl }}"

- name: Add apache vhosts configuration.
  template:
    src: "{{ apache_vhosts_template }}"
    dest: "{{ apache_conf_path }}/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts
