---
- name: Configure Apache.
  lineinfile:
    dest: "{{ apache_server_root }}/{{ apache_daemon }}.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: "{{ apache_ports_configuration_items }}"
  notify: restart apache

- name: Add apache vhosts configuration.
  template:
    src: "{{ apache_vhosts_template }}"
    dest: "{{ apache_conf_path }}/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts

- name: Override default Apache configurations.
  template:
    src: "{{ item.src }}"
    dest: "{{ apache_server_root }}/{{ item.dest }}"
    force: "{{ item.force | default('yes') }}"
  notify: restart apache
  with_items: apache_config_files
