---
- name: Configure Apache.
  lineinfile:
    dest: "{{ apache_server_root }}/conf/{{ apache_daemon }}.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: apache_ports_configuration_items
  notify: restart apache
  when: apache_httpdconf_file is not defined

- name: Override default Apache conf.
  template:
    src: "{{ item.src }}"
    dest: "{{ apache_server_root }}/{{ item.dest }}"
    force: "{{ item.force | default('yes') }}"
  notify: restart apache
  with_items: apache_config_files

- name: Add apache vhosts configuration.
  template:
    src: "vhosts-{{ apache_vhosts_version }}.conf.j2"
    dest: "{{ apache_conf_path }}/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts
